### ISSUE TITLE
there is no PurchaseButton in SubscriptionView 

### ISSUE THREAD

**Issue by shaunthegeek** [russell-archer/StoreHelperDemo#2]
SubscriptionView result:

> You are not subscribed to xxx

But how can I subscribe it?

<img width="792" alt="image" src="https://user-images.githubusercontent.com/4971414/196452488-9a579381-c800-425e-a68b-203ce41d5b32.png">

**Comment by russell-archer** [comment]
You subscribe/purchase products through the Product List page. It also shows you what products you've purchased/subscribed to:

![demo1](https://user-images.githubusercontent.com/6470403/196479407-bc653d10-a3d2-46cf-8aca-3581b61ab1cd.png)

![demo2](https://user-images.githubusercontent.com/6470403/196479439-036912b0-37ba-4d75-b75f-e130a4b6fda6.png)

![demo3](https://user-images.githubusercontent.com/6470403/196479441-a1bb2703-202d-4036-b96c-347b39630831.png)

![demo4](https://user-images.githubusercontent.com/6470403/196479442-34905a16-2ed0-461f-975c-eb9e2169e40f.png)

![demo5](https://user-images.githubusercontent.com/6470403/196479445-9c2cef44-cb1e-4e1c-a8eb-2559ca9fa51d.png)

The Subscriptions page was added to the in response to a question about how to get the subscription status for a list of products. This is only for demo purposes. Clearly you won't use this UI for a real-world app.

Hope this helps.
