### ISSUE TITLE
Product List page is freezing after purchase

### ISSUE THREAD

**Issue by akardas16** [russell-archer/StoreHelperDemo#4]
Unfortunately I can still produce that bug. (I cant scroll it)

**Comment by russell-archer** [comment]
No, it's definately fixed. I just got the most recent version of StoreHelperDemo, made sure the StoreHelper package was up-to-date (in Xcode: Packages > Update to Latest Package Versions) and then ran it in the simulator. I was able to scroll the list of purchases, purchase a product and then scroll the list again.

You can see it here:
https://www.dropbox.com/s/n68kvmkgtvm5kwh/StoreHelperDemo-2Feb2023.gif?dl=0

Russell
